/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.parser;

import src.promela.node.*;
import src.promela.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 0;
    }

    @Override
    public void caseTBang(@SuppressWarnings("unused") TBang node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComplement(@SuppressWarnings("unused") TComplement node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMultop(@SuppressWarnings("unused") TMultop node)
    {
        this.index = 3;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 4;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 5;
    }

    @Override
    public void caseTShiftop(@SuppressWarnings("unused") TShiftop node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEqop(@SuppressWarnings("unused") TEqop node)
    {
        this.index = 7;
    }

    @Override
    public void caseTBitand(@SuppressWarnings("unused") TBitand node)
    {
        this.index = 8;
    }

    @Override
    public void caseTBitor(@SuppressWarnings("unused") TBitor node)
    {
        this.index = 9;
    }

    @Override
    public void caseTBitxor(@SuppressWarnings("unused") TBitxor node)
    {
        this.index = 10;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 11;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 12;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 13;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRelop(@SuppressWarnings("unused") TRelop node)
    {
        this.index = 15;
    }

    @Override
    public void caseTLParenthese(@SuppressWarnings("unused") TLParenthese node)
    {
        this.index = 16;
    }

    @Override
    public void caseTRParenthese(@SuppressWarnings("unused") TRParenthese node)
    {
        this.index = 17;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 18;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 19;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 20;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 21;
    }

    @Override
    public void caseTSeparator(@SuppressWarnings("unused") TSeparator node)
    {
        this.index = 22;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 23;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 24;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 25;
    }

    @Override
    public void caseTColonColon(@SuppressWarnings("unused") TColonColon node)
    {
        this.index = 26;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 27;
    }

    @Override
    public void caseTPlusPlus(@SuppressWarnings("unused") TPlusPlus node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMinusMinus(@SuppressWarnings("unused") TMinusMinus node)
    {
        this.index = 29;
    }

    @Override
    public void caseTRightarrow(@SuppressWarnings("unused") TRightarrow node)
    {
        this.index = 30;
    }

    @Override
    public void caseTBangBang(@SuppressWarnings("unused") TBangBang node)
    {
        this.index = 31;
    }

    @Override
    public void caseTQueryQuery(@SuppressWarnings("unused") TQueryQuery node)
    {
        this.index = 32;
    }

    @Override
    public void caseTQuery(@SuppressWarnings("unused") TQuery node)
    {
        this.index = 33;
    }

    @Override
    public void caseTUnderscore(@SuppressWarnings("unused") TUnderscore node)
    {
        this.index = 34;
    }

    @Override
    public void caseTQuotes(@SuppressWarnings("unused") TQuotes node)
    {
        this.index = 35;
    }

    @Override
    public void caseTAt(@SuppressWarnings("unused") TAt node)
    {
        this.index = 36;
    }

    @Override
    public void caseTActivetok(@SuppressWarnings("unused") TActivetok node)
    {
        this.index = 37;
    }

    @Override
    public void caseTAssert(@SuppressWarnings("unused") TAssert node)
    {
        this.index = 38;
    }

    @Override
    public void caseTAtomic(@SuppressWarnings("unused") TAtomic node)
    {
        this.index = 39;
    }

    @Override
    public void caseTBit(@SuppressWarnings("unused") TBit node)
    {
        this.index = 40;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 41;
    }

    @Override
    public void caseTBreak(@SuppressWarnings("unused") TBreak node)
    {
        this.index = 42;
    }

    @Override
    public void caseTByte(@SuppressWarnings("unused") TByte node)
    {
        this.index = 43;
    }

    @Override
    public void caseTChanop(@SuppressWarnings("unused") TChanop node)
    {
        this.index = 44;
    }

    @Override
    public void caseTChan(@SuppressWarnings("unused") TChan node)
    {
        this.index = 45;
    }

    @Override
    public void caseTDStep(@SuppressWarnings("unused") TDStep node)
    {
        this.index = 46;
    }

    @Override
    public void caseTDo(@SuppressWarnings("unused") TDo node)
    {
        this.index = 47;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 48;
    }

    @Override
    public void caseTEnabled(@SuppressWarnings("unused") TEnabled node)
    {
        this.index = 49;
    }

    @Override
    public void caseTEval(@SuppressWarnings("unused") TEval node)
    {
        this.index = 50;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 51;
    }

    @Override
    public void caseTFi(@SuppressWarnings("unused") TFi node)
    {
        this.index = 52;
    }

    @Override
    public void caseTGoto(@SuppressWarnings("unused") TGoto node)
    {
        this.index = 53;
    }

    @Override
    public void caseTHidden(@SuppressWarnings("unused") THidden node)
    {
        this.index = 54;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 55;
    }

    @Override
    public void caseTInittok(@SuppressWarnings("unused") TInittok node)
    {
        this.index = 56;
    }

    @Override
    public void caseTInlinetok(@SuppressWarnings("unused") TInlinetok node)
    {
        this.index = 57;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 58;
    }

    @Override
    public void caseTLen(@SuppressWarnings("unused") TLen node)
    {
        this.index = 59;
    }

    @Override
    public void caseTMtypetok(@SuppressWarnings("unused") TMtypetok node)
    {
        this.index = 60;
    }

    @Override
    public void caseTNevertok(@SuppressWarnings("unused") TNevertok node)
    {
        this.index = 61;
    }

    @Override
    public void caseTNotrace(@SuppressWarnings("unused") TNotrace node)
    {
        this.index = 62;
    }

    @Override
    public void caseTNp(@SuppressWarnings("unused") TNp node)
    {
        this.index = 63;
    }

    @Override
    public void caseTOd(@SuppressWarnings("unused") TOd node)
    {
        this.index = 64;
    }

    @Override
    public void caseTOf(@SuppressWarnings("unused") TOf node)
    {
        this.index = 65;
    }

    @Override
    public void caseTPcValue(@SuppressWarnings("unused") TPcValue node)
    {
        this.index = 66;
    }

    @Override
    public void caseTPid(@SuppressWarnings("unused") TPid node)
    {
        this.index = 67;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 68;
    }

    @Override
    public void caseTPrioritytok(@SuppressWarnings("unused") TPrioritytok node)
    {
        this.index = 69;
    }

    @Override
    public void caseTProcessid(@SuppressWarnings("unused") TProcessid node)
    {
        this.index = 70;
    }

    @Override
    public void caseTProctypetok(@SuppressWarnings("unused") TProctypetok node)
    {
        this.index = 71;
    }

    @Override
    public void caseTProvided(@SuppressWarnings("unused") TProvided node)
    {
        this.index = 72;
    }

    @Override
    public void caseTRun(@SuppressWarnings("unused") TRun node)
    {
        this.index = 73;
    }

    @Override
    public void caseTShort(@SuppressWarnings("unused") TShort node)
    {
        this.index = 74;
    }

    @Override
    public void caseTShow(@SuppressWarnings("unused") TShow node)
    {
        this.index = 75;
    }

    @Override
    public void caseTSkip(@SuppressWarnings("unused") TSkip node)
    {
        this.index = 76;
    }

    @Override
    public void caseTTimeout(@SuppressWarnings("unused") TTimeout node)
    {
        this.index = 77;
    }

    @Override
    public void caseTTracetok(@SuppressWarnings("unused") TTracetok node)
    {
        this.index = 78;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 79;
    }

    @Override
    public void caseTTypedef(@SuppressWarnings("unused") TTypedef node)
    {
        this.index = 80;
    }

    @Override
    public void caseTUnless(@SuppressWarnings("unused") TUnless node)
    {
        this.index = 81;
    }

    @Override
    public void caseTXr(@SuppressWarnings("unused") TXr node)
    {
        this.index = 82;
    }

    @Override
    public void caseTXs(@SuppressWarnings("unused") TXs node)
    {
        this.index = 83;
    }

    @Override
    public void caseTTemplatetok(@SuppressWarnings("unused") TTemplatetok node)
    {
        this.index = 84;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 85;
    }

    @Override
    public void caseTOver(@SuppressWarnings("unused") TOver node)
    {
        this.index = 86;
    }

    @Override
    public void caseTName(@SuppressWarnings("unused") TName node)
    {
        this.index = 87;
    }

    @Override
    public void caseTByteliteral(@SuppressWarnings("unused") TByteliteral node)
    {
        this.index = 88;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 89;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 90;
    }
}
