/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AAssertStmnt extends PStmnt
{
    private TAssert _assert_;
    private PExpr _expr_;

    public AAssertStmnt()
    {
        // Constructor
    }

    public AAssertStmnt(
        @SuppressWarnings("hiding") TAssert _assert_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setAssert(_assert_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AAssertStmnt(
            cloneNode(this._assert_),
            cloneNode(this._expr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertStmnt(this);
    }

    public TAssert getAssert()
    {
        return this._assert_;
    }

    public void setAssert(TAssert node)
    {
        if(this._assert_ != null)
        {
            this._assert_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assert_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assert_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assert_ == child)
        {
            this._assert_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assert_ == oldChild)
        {
            setAssert((TAssert) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
