/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AConstRecvArg extends PRecvArg
{
    private PConst _const_;

    public AConstRecvArg()
    {
        // Constructor
    }

    public AConstRecvArg(
        @SuppressWarnings("hiding") PConst _const_)
    {
        // Constructor
        setConst(_const_);

    }

    @Override
    public Object clone()
    {
        return new AConstRecvArg(
            cloneNode(this._const_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstRecvArg(this);
    }

    public PConst getConst()
    {
        return this._const_;
    }

    public void setConst(PConst node)
    {
        if(this._const_ != null)
        {
            this._const_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._const_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._const_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._const_ == child)
        {
            this._const_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._const_ == oldChild)
        {
            setConst((PConst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
