/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ADecrementAssignment extends PAssignment
{
    private PVarref _varref_;
    private TMinusMinus _minusMinus_;

    public ADecrementAssignment()
    {
        // Constructor
    }

    public ADecrementAssignment(
        @SuppressWarnings("hiding") PVarref _varref_,
        @SuppressWarnings("hiding") TMinusMinus _minusMinus_)
    {
        // Constructor
        setVarref(_varref_);

        setMinusMinus(_minusMinus_);

    }

    @Override
    public Object clone()
    {
        return new ADecrementAssignment(
            cloneNode(this._varref_),
            cloneNode(this._minusMinus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecrementAssignment(this);
    }

    public PVarref getVarref()
    {
        return this._varref_;
    }

    public void setVarref(PVarref node)
    {
        if(this._varref_ != null)
        {
            this._varref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varref_ = node;
    }

    public TMinusMinus getMinusMinus()
    {
        return this._minusMinus_;
    }

    public void setMinusMinus(TMinusMinus node)
    {
        if(this._minusMinus_ != null)
        {
            this._minusMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusMinus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varref_)
            + toString(this._minusMinus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varref_ == child)
        {
            this._varref_ = null;
            return;
        }

        if(this._minusMinus_ == child)
        {
            this._minusMinus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varref_ == oldChild)
        {
            setVarref((PVarref) newChild);
            return;
        }

        if(this._minusMinus_ == oldChild)
        {
            setMinusMinus((TMinusMinus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
