/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AElseStmnt extends PStmnt
{
    private TElse _else_;

    public AElseStmnt()
    {
        // Constructor
    }

    public AElseStmnt(
        @SuppressWarnings("hiding") TElse _else_)
    {
        // Constructor
        setElse(_else_);

    }

    @Override
    public Object clone()
    {
        return new AElseStmnt(
            cloneNode(this._else_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseStmnt(this);
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._else_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
