/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AFifopollReceive extends PReceive
{
    private PVarref _varref_;
    private TQuery _query_;
    private TLt _lt_;
    private PRecvArgs _recvArgs_;
    private TGt _gt_;

    public AFifopollReceive()
    {
        // Constructor
    }

    public AFifopollReceive(
        @SuppressWarnings("hiding") PVarref _varref_,
        @SuppressWarnings("hiding") TQuery _query_,
        @SuppressWarnings("hiding") TLt _lt_,
        @SuppressWarnings("hiding") PRecvArgs _recvArgs_,
        @SuppressWarnings("hiding") TGt _gt_)
    {
        // Constructor
        setVarref(_varref_);

        setQuery(_query_);

        setLt(_lt_);

        setRecvArgs(_recvArgs_);

        setGt(_gt_);

    }

    @Override
    public Object clone()
    {
        return new AFifopollReceive(
            cloneNode(this._varref_),
            cloneNode(this._query_),
            cloneNode(this._lt_),
            cloneNode(this._recvArgs_),
            cloneNode(this._gt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFifopollReceive(this);
    }

    public PVarref getVarref()
    {
        return this._varref_;
    }

    public void setVarref(PVarref node)
    {
        if(this._varref_ != null)
        {
            this._varref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varref_ = node;
    }

    public TQuery getQuery()
    {
        return this._query_;
    }

    public void setQuery(TQuery node)
    {
        if(this._query_ != null)
        {
            this._query_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._query_ = node;
    }

    public TLt getLt()
    {
        return this._lt_;
    }

    public void setLt(TLt node)
    {
        if(this._lt_ != null)
        {
            this._lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lt_ = node;
    }

    public PRecvArgs getRecvArgs()
    {
        return this._recvArgs_;
    }

    public void setRecvArgs(PRecvArgs node)
    {
        if(this._recvArgs_ != null)
        {
            this._recvArgs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recvArgs_ = node;
    }

    public TGt getGt()
    {
        return this._gt_;
    }

    public void setGt(TGt node)
    {
        if(this._gt_ != null)
        {
            this._gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varref_)
            + toString(this._query_)
            + toString(this._lt_)
            + toString(this._recvArgs_)
            + toString(this._gt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varref_ == child)
        {
            this._varref_ = null;
            return;
        }

        if(this._query_ == child)
        {
            this._query_ = null;
            return;
        }

        if(this._lt_ == child)
        {
            this._lt_ = null;
            return;
        }

        if(this._recvArgs_ == child)
        {
            this._recvArgs_ = null;
            return;
        }

        if(this._gt_ == child)
        {
            this._gt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varref_ == oldChild)
        {
            setVarref((PVarref) newChild);
            return;
        }

        if(this._query_ == oldChild)
        {
            setQuery((TQuery) newChild);
            return;
        }

        if(this._lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(this._recvArgs_ == oldChild)
        {
            setRecvArgs((PRecvArgs) newChild);
            return;
        }

        if(this._gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
