/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AIfStmnt extends PStmnt
{
    private TIf _if_;
    private POptions _options_;
    private TFi _fi_;

    public AIfStmnt()
    {
        // Constructor
    }

    public AIfStmnt(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") POptions _options_,
        @SuppressWarnings("hiding") TFi _fi_)
    {
        // Constructor
        setIf(_if_);

        setOptions(_options_);

        setFi(_fi_);

    }

    @Override
    public Object clone()
    {
        return new AIfStmnt(
            cloneNode(this._if_),
            cloneNode(this._options_),
            cloneNode(this._fi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStmnt(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public POptions getOptions()
    {
        return this._options_;
    }

    public void setOptions(POptions node)
    {
        if(this._options_ != null)
        {
            this._options_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._options_ = node;
    }

    public TFi getFi()
    {
        return this._fi_;
    }

    public void setFi(TFi node)
    {
        if(this._fi_ != null)
        {
            this._fi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._options_)
            + toString(this._fi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._options_ == child)
        {
            this._options_ = null;
            return;
        }

        if(this._fi_ == child)
        {
            this._fi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._options_ == oldChild)
        {
            setOptions((POptions) newChild);
            return;
        }

        if(this._fi_ == oldChild)
        {
            setFi((TFi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
