/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AIncrementAssignment extends PAssignment
{
    private PVarref _varref_;
    private TPlusPlus _plusPlus_;

    public AIncrementAssignment()
    {
        // Constructor
    }

    public AIncrementAssignment(
        @SuppressWarnings("hiding") PVarref _varref_,
        @SuppressWarnings("hiding") TPlusPlus _plusPlus_)
    {
        // Constructor
        setVarref(_varref_);

        setPlusPlus(_plusPlus_);

    }

    @Override
    public Object clone()
    {
        return new AIncrementAssignment(
            cloneNode(this._varref_),
            cloneNode(this._plusPlus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIncrementAssignment(this);
    }

    public PVarref getVarref()
    {
        return this._varref_;
    }

    public void setVarref(PVarref node)
    {
        if(this._varref_ != null)
        {
            this._varref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varref_ = node;
    }

    public TPlusPlus getPlusPlus()
    {
        return this._plusPlus_;
    }

    public void setPlusPlus(TPlusPlus node)
    {
        if(this._plusPlus_ != null)
        {
            this._plusPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varref_)
            + toString(this._plusPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varref_ == child)
        {
            this._varref_ = null;
            return;
        }

        if(this._plusPlus_ == child)
        {
            this._plusPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varref_ == oldChild)
        {
            setVarref((PVarref) newChild);
            return;
        }

        if(this._plusPlus_ == oldChild)
        {
            setPlusPlus((TPlusPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
