/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AListSendArgs extends PSendArgs
{
    private PArgLst _argLst_;

    public AListSendArgs()
    {
        // Constructor
    }

    public AListSendArgs(
        @SuppressWarnings("hiding") PArgLst _argLst_)
    {
        // Constructor
        setArgLst(_argLst_);

    }

    @Override
    public Object clone()
    {
        return new AListSendArgs(
            cloneNode(this._argLst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListSendArgs(this);
    }

    public PArgLst getArgLst()
    {
        return this._argLst_;
    }

    public void setArgLst(PArgLst node)
    {
        if(this._argLst_ != null)
        {
            this._argLst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argLst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._argLst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._argLst_ == child)
        {
            this._argLst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._argLst_ == oldChild)
        {
            setArgLst((PArgLst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
