/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AManyheadedRecvArgs extends PRecvArgs
{
    private PRecvArg _recvArg_;
    private TLParenthese _lParenthese_;
    private PRecvArgs _recvArgs_;
    private TRParenthese _rParenthese_;

    public AManyheadedRecvArgs()
    {
        // Constructor
    }

    public AManyheadedRecvArgs(
        @SuppressWarnings("hiding") PRecvArg _recvArg_,
        @SuppressWarnings("hiding") TLParenthese _lParenthese_,
        @SuppressWarnings("hiding") PRecvArgs _recvArgs_,
        @SuppressWarnings("hiding") TRParenthese _rParenthese_)
    {
        // Constructor
        setRecvArg(_recvArg_);

        setLParenthese(_lParenthese_);

        setRecvArgs(_recvArgs_);

        setRParenthese(_rParenthese_);

    }

    @Override
    public Object clone()
    {
        return new AManyheadedRecvArgs(
            cloneNode(this._recvArg_),
            cloneNode(this._lParenthese_),
            cloneNode(this._recvArgs_),
            cloneNode(this._rParenthese_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyheadedRecvArgs(this);
    }

    public PRecvArg getRecvArg()
    {
        return this._recvArg_;
    }

    public void setRecvArg(PRecvArg node)
    {
        if(this._recvArg_ != null)
        {
            this._recvArg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recvArg_ = node;
    }

    public TLParenthese getLParenthese()
    {
        return this._lParenthese_;
    }

    public void setLParenthese(TLParenthese node)
    {
        if(this._lParenthese_ != null)
        {
            this._lParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParenthese_ = node;
    }

    public PRecvArgs getRecvArgs()
    {
        return this._recvArgs_;
    }

    public void setRecvArgs(PRecvArgs node)
    {
        if(this._recvArgs_ != null)
        {
            this._recvArgs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recvArgs_ = node;
    }

    public TRParenthese getRParenthese()
    {
        return this._rParenthese_;
    }

    public void setRParenthese(TRParenthese node)
    {
        if(this._rParenthese_ != null)
        {
            this._rParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParenthese_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._recvArg_)
            + toString(this._lParenthese_)
            + toString(this._recvArgs_)
            + toString(this._rParenthese_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._recvArg_ == child)
        {
            this._recvArg_ = null;
            return;
        }

        if(this._lParenthese_ == child)
        {
            this._lParenthese_ = null;
            return;
        }

        if(this._recvArgs_ == child)
        {
            this._recvArgs_ = null;
            return;
        }

        if(this._rParenthese_ == child)
        {
            this._rParenthese_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._recvArg_ == oldChild)
        {
            setRecvArg((PRecvArg) newChild);
            return;
        }

        if(this._lParenthese_ == oldChild)
        {
            setLParenthese((TLParenthese) newChild);
            return;
        }

        if(this._recvArgs_ == oldChild)
        {
            setRecvArgs((PRecvArgs) newChild);
            return;
        }

        if(this._rParenthese_ == oldChild)
        {
            setRParenthese((TRParenthese) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
