/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import java.util.*;
import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ANormalSpec extends PSpec
{
    private final LinkedList<PModule> _module_ = new LinkedList<PModule>();

    public ANormalSpec()
    {
        // Constructor
    }

    public ANormalSpec(
        @SuppressWarnings("hiding") List<PModule> _module_)
    {
        // Constructor
        setModule(_module_);

    }

    @Override
    public Object clone()
    {
        return new ANormalSpec(
            cloneList(this._module_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANormalSpec(this);
    }

    public LinkedList<PModule> getModule()
    {
        return this._module_;
    }

    public void setModule(List<PModule> list)
    {
        this._module_.clear();
        this._module_.addAll(list);
        for(PModule e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._module_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._module_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PModule> i = this._module_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PModule) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
