/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ANullDeclLst extends PDeclLst
{

    public ANullDeclLst()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANullDeclLst();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANullDeclLst(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
