/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AOneVarreflst extends PVarreflst
{
    private PVarref _varref_;

    public AOneVarreflst()
    {
        // Constructor
    }

    public AOneVarreflst(
        @SuppressWarnings("hiding") PVarref _varref_)
    {
        // Constructor
        setVarref(_varref_);

    }

    @Override
    public Object clone()
    {
        return new AOneVarreflst(
            cloneNode(this._varref_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneVarreflst(this);
    }

    public PVarref getVarref()
    {
        return this._varref_;
    }

    public void setVarref(PVarref node)
    {
        if(this._varref_ != null)
        {
            this._varref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varref_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varref_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varref_ == child)
        {
            this._varref_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varref_ == oldChild)
        {
            setVarref((PVarref) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
