/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AOneTypenamelst extends PTypenamelst
{
    private PTypename _typename_;

    public AOneTypenamelst()
    {
        // Constructor
    }

    public AOneTypenamelst(
        @SuppressWarnings("hiding") PTypename _typename_)
    {
        // Constructor
        setTypename(_typename_);

    }

    @Override
    public Object clone()
    {
        return new AOneTypenamelst(
            cloneNode(this._typename_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOneTypenamelst(this);
    }

    public PTypename getTypename()
    {
        return this._typename_;
    }

    public void setTypename(PTypename node)
    {
        if(this._typename_ != null)
        {
            this._typename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typename_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typename_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typename_ == child)
        {
            this._typename_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typename_ == oldChild)
        {
            setTypename((PTypename) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
