/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class APidTypename extends PTypename
{
    private TPid _pid_;

    public APidTypename()
    {
        // Constructor
    }

    public APidTypename(
        @SuppressWarnings("hiding") TPid _pid_)
    {
        // Constructor
        setPid(_pid_);

    }

    @Override
    public Object clone()
    {
        return new APidTypename(
            cloneNode(this._pid_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPidTypename(this);
    }

    public TPid getPid()
    {
        return this._pid_;
    }

    public void setPid(TPid node)
    {
        if(this._pid_ != null)
        {
            this._pid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pid_ == child)
        {
            this._pid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pid_ == oldChild)
        {
            setPid((TPid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
