/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class APidConst extends PConst
{
    private TProcessid _processid_;

    public APidConst()
    {
        // Constructor
    }

    public APidConst(
        @SuppressWarnings("hiding") TProcessid _processid_)
    {
        // Constructor
        setProcessid(_processid_);

    }

    @Override
    public Object clone()
    {
        return new APidConst(
            cloneNode(this._processid_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPidConst(this);
    }

    public TProcessid getProcessid()
    {
        return this._processid_;
    }

    public void setProcessid(TProcessid node)
    {
        if(this._processid_ != null)
        {
            this._processid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._processid_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._processid_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._processid_ == child)
        {
            this._processid_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._processid_ == oldChild)
        {
            setProcessid((TProcessid) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
