/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AProctype extends PProctype
{
    private PActive _active_;
    private TProctypetok _proctypetok_;
    private TName _name_;
    private TLParenthese _lParenthese_;
    private PParamLst _paramLst_;
    private TRParenthese _rParenthese_;
    private PPriority _priority_;
    private PEnabler _enabler_;
    private TLBrace _lBrace_;
    private PSequence _sequence_;
    private TRBrace _rBrace_;

    public AProctype()
    {
        // Constructor
    }

    public AProctype(
        @SuppressWarnings("hiding") PActive _active_,
        @SuppressWarnings("hiding") TProctypetok _proctypetok_,
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") TLParenthese _lParenthese_,
        @SuppressWarnings("hiding") PParamLst _paramLst_,
        @SuppressWarnings("hiding") TRParenthese _rParenthese_,
        @SuppressWarnings("hiding") PPriority _priority_,
        @SuppressWarnings("hiding") PEnabler _enabler_,
        @SuppressWarnings("hiding") TLBrace _lBrace_,
        @SuppressWarnings("hiding") PSequence _sequence_,
        @SuppressWarnings("hiding") TRBrace _rBrace_)
    {
        // Constructor
        setActive(_active_);

        setProctypetok(_proctypetok_);

        setName(_name_);

        setLParenthese(_lParenthese_);

        setParamLst(_paramLst_);

        setRParenthese(_rParenthese_);

        setPriority(_priority_);

        setEnabler(_enabler_);

        setLBrace(_lBrace_);

        setSequence(_sequence_);

        setRBrace(_rBrace_);

    }

    @Override
    public Object clone()
    {
        return new AProctype(
            cloneNode(this._active_),
            cloneNode(this._proctypetok_),
            cloneNode(this._name_),
            cloneNode(this._lParenthese_),
            cloneNode(this._paramLst_),
            cloneNode(this._rParenthese_),
            cloneNode(this._priority_),
            cloneNode(this._enabler_),
            cloneNode(this._lBrace_),
            cloneNode(this._sequence_),
            cloneNode(this._rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProctype(this);
    }

    public PActive getActive()
    {
        return this._active_;
    }

    public void setActive(PActive node)
    {
        if(this._active_ != null)
        {
            this._active_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._active_ = node;
    }

    public TProctypetok getProctypetok()
    {
        return this._proctypetok_;
    }

    public void setProctypetok(TProctypetok node)
    {
        if(this._proctypetok_ != null)
        {
            this._proctypetok_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._proctypetok_ = node;
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TLParenthese getLParenthese()
    {
        return this._lParenthese_;
    }

    public void setLParenthese(TLParenthese node)
    {
        if(this._lParenthese_ != null)
        {
            this._lParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParenthese_ = node;
    }

    public PParamLst getParamLst()
    {
        return this._paramLst_;
    }

    public void setParamLst(PParamLst node)
    {
        if(this._paramLst_ != null)
        {
            this._paramLst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramLst_ = node;
    }

    public TRParenthese getRParenthese()
    {
        return this._rParenthese_;
    }

    public void setRParenthese(TRParenthese node)
    {
        if(this._rParenthese_ != null)
        {
            this._rParenthese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParenthese_ = node;
    }

    public PPriority getPriority()
    {
        return this._priority_;
    }

    public void setPriority(PPriority node)
    {
        if(this._priority_ != null)
        {
            this._priority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._priority_ = node;
    }

    public PEnabler getEnabler()
    {
        return this._enabler_;
    }

    public void setEnabler(PEnabler node)
    {
        if(this._enabler_ != null)
        {
            this._enabler_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enabler_ = node;
    }

    public TLBrace getLBrace()
    {
        return this._lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(this._lBrace_ != null)
        {
            this._lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrace_ = node;
    }

    public PSequence getSequence()
    {
        return this._sequence_;
    }

    public void setSequence(PSequence node)
    {
        if(this._sequence_ != null)
        {
            this._sequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sequence_ = node;
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._active_)
            + toString(this._proctypetok_)
            + toString(this._name_)
            + toString(this._lParenthese_)
            + toString(this._paramLst_)
            + toString(this._rParenthese_)
            + toString(this._priority_)
            + toString(this._enabler_)
            + toString(this._lBrace_)
            + toString(this._sequence_)
            + toString(this._rBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._active_ == child)
        {
            this._active_ = null;
            return;
        }

        if(this._proctypetok_ == child)
        {
            this._proctypetok_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._lParenthese_ == child)
        {
            this._lParenthese_ = null;
            return;
        }

        if(this._paramLst_ == child)
        {
            this._paramLst_ = null;
            return;
        }

        if(this._rParenthese_ == child)
        {
            this._rParenthese_ = null;
            return;
        }

        if(this._priority_ == child)
        {
            this._priority_ = null;
            return;
        }

        if(this._enabler_ == child)
        {
            this._enabler_ = null;
            return;
        }

        if(this._lBrace_ == child)
        {
            this._lBrace_ = null;
            return;
        }

        if(this._sequence_ == child)
        {
            this._sequence_ = null;
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._active_ == oldChild)
        {
            setActive((PActive) newChild);
            return;
        }

        if(this._proctypetok_ == oldChild)
        {
            setProctypetok((TProctypetok) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._lParenthese_ == oldChild)
        {
            setLParenthese((TLParenthese) newChild);
            return;
        }

        if(this._paramLst_ == oldChild)
        {
            setParamLst((PParamLst) newChild);
            return;
        }

        if(this._rParenthese_ == oldChild)
        {
            setRParenthese((TRParenthese) newChild);
            return;
        }

        if(this._priority_ == oldChild)
        {
            setPriority((PPriority) newChild);
            return;
        }

        if(this._enabler_ == oldChild)
        {
            setEnabler((PEnabler) newChild);
            return;
        }

        if(this._lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(this._sequence_ == oldChild)
        {
            setSequence((PSequence) newChild);
            return;
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
