/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ARecvPollFactor extends PFactor
{
    private PRecvPoll _recvPoll_;

    public ARecvPollFactor()
    {
        // Constructor
    }

    public ARecvPollFactor(
        @SuppressWarnings("hiding") PRecvPoll _recvPoll_)
    {
        // Constructor
        setRecvPoll(_recvPoll_);

    }

    @Override
    public Object clone()
    {
        return new ARecvPollFactor(
            cloneNode(this._recvPoll_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecvPollFactor(this);
    }

    public PRecvPoll getRecvPoll()
    {
        return this._recvPoll_;
    }

    public void setRecvPoll(PRecvPoll node)
    {
        if(this._recvPoll_ != null)
        {
            this._recvPoll_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recvPoll_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._recvPoll_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._recvPoll_ == child)
        {
            this._recvPoll_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._recvPoll_ == oldChild)
        {
            setRecvPoll((PRecvPoll) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
