/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AReceiveStmnt extends PStmnt
{
    private PReceive _receive_;

    public AReceiveStmnt()
    {
        // Constructor
    }

    public AReceiveStmnt(
        @SuppressWarnings("hiding") PReceive _receive_)
    {
        // Constructor
        setReceive(_receive_);

    }

    @Override
    public Object clone()
    {
        return new AReceiveStmnt(
            cloneNode(this._receive_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReceiveStmnt(this);
    }

    public PReceive getReceive()
    {
        return this._receive_;
    }

    public void setReceive(PReceive node)
    {
        if(this._receive_ != null)
        {
            this._receive_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._receive_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._receive_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._receive_ == child)
        {
            this._receive_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._receive_ == oldChild)
        {
            setReceive((PReceive) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
