/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ARecordVarref extends PVarref
{
    private PVarref _varref_;
    private TDot _dot_;
    private TName _name_;
    private PArrayref _arrayref_;

    public ARecordVarref()
    {
        // Constructor
    }

    public ARecordVarref(
        @SuppressWarnings("hiding") PVarref _varref_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") PArrayref _arrayref_)
    {
        // Constructor
        setVarref(_varref_);

        setDot(_dot_);

        setName(_name_);

        setArrayref(_arrayref_);

    }

    @Override
    public Object clone()
    {
        return new ARecordVarref(
            cloneNode(this._varref_),
            cloneNode(this._dot_),
            cloneNode(this._name_),
            cloneNode(this._arrayref_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecordVarref(this);
    }

    public PVarref getVarref()
    {
        return this._varref_;
    }

    public void setVarref(PVarref node)
    {
        if(this._varref_ != null)
        {
            this._varref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varref_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PArrayref getArrayref()
    {
        return this._arrayref_;
    }

    public void setArrayref(PArrayref node)
    {
        if(this._arrayref_ != null)
        {
            this._arrayref_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayref_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varref_)
            + toString(this._dot_)
            + toString(this._name_)
            + toString(this._arrayref_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varref_ == child)
        {
            this._varref_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._arrayref_ == child)
        {
            this._arrayref_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varref_ == oldChild)
        {
            setVarref((PVarref) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._arrayref_ == oldChild)
        {
            setArrayref((PArrayref) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
