/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AShowVisible extends PVisible
{
    private TShow _show_;

    public AShowVisible()
    {
        // Constructor
    }

    public AShowVisible(
        @SuppressWarnings("hiding") TShow _show_)
    {
        // Constructor
        setShow(_show_);

    }

    @Override
    public Object clone()
    {
        return new AShowVisible(
            cloneNode(this._show_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShowVisible(this);
    }

    public TShow getShow()
    {
        return this._show_;
    }

    public void setShow(TShow node)
    {
        if(this._show_ != null)
        {
            this._show_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._show_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._show_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._show_ == child)
        {
            this._show_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._show_ == oldChild)
        {
            setShow((TShow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
