/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleBitorExpr extends PBitorExpr
{
    private PBitxorExpr _bitxorExpr_;

    public ASimpleBitorExpr()
    {
        // Constructor
    }

    public ASimpleBitorExpr(
        @SuppressWarnings("hiding") PBitxorExpr _bitxorExpr_)
    {
        // Constructor
        setBitxorExpr(_bitxorExpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleBitorExpr(
            cloneNode(this._bitxorExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleBitorExpr(this);
    }

    public PBitxorExpr getBitxorExpr()
    {
        return this._bitxorExpr_;
    }

    public void setBitxorExpr(PBitxorExpr node)
    {
        if(this._bitxorExpr_ != null)
        {
            this._bitxorExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bitxorExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bitxorExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bitxorExpr_ == child)
        {
            this._bitxorExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bitxorExpr_ == oldChild)
        {
            setBitxorExpr((PBitxorExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
