/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleBitxorExpr extends PBitxorExpr
{
    private PBitandExpr _bitandExpr_;

    public ASimpleBitxorExpr()
    {
        // Constructor
    }

    public ASimpleBitxorExpr(
        @SuppressWarnings("hiding") PBitandExpr _bitandExpr_)
    {
        // Constructor
        setBitandExpr(_bitandExpr_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleBitxorExpr(
            cloneNode(this._bitandExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleBitxorExpr(this);
    }

    public PBitandExpr getBitandExpr()
    {
        return this._bitandExpr_;
    }

    public void setBitandExpr(PBitandExpr node)
    {
        if(this._bitandExpr_ != null)
        {
            this._bitandExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bitandExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bitandExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bitandExpr_ == child)
        {
            this._bitandExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bitandExpr_ == oldChild)
        {
            setBitandExpr((PBitandExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
