/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AUtypeModule extends PModule
{
    private PUtype _utype_;

    public AUtypeModule()
    {
        // Constructor
    }

    public AUtypeModule(
        @SuppressWarnings("hiding") PUtype _utype_)
    {
        // Constructor
        setUtype(_utype_);

    }

    @Override
    public Object clone()
    {
        return new AUtypeModule(
            cloneNode(this._utype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUtypeModule(this);
    }

    public PUtype getUtype()
    {
        return this._utype_;
    }

    public void setUtype(PUtype node)
    {
        if(this._utype_ != null)
        {
            this._utype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._utype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._utype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._utype_ == child)
        {
            this._utype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._utype_ == oldChild)
        {
            setUtype((PUtype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
