/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class AVarschansModule extends PModule
{
    private PDeclLst _declLst_;

    public AVarschansModule()
    {
        // Constructor
    }

    public AVarschansModule(
        @SuppressWarnings("hiding") PDeclLst _declLst_)
    {
        // Constructor
        setDeclLst(_declLst_);

    }

    @Override
    public Object clone()
    {
        return new AVarschansModule(
            cloneNode(this._declLst_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarschansModule(this);
    }

    public PDeclLst getDeclLst()
    {
        return this._declLst_;
    }

    public void setDeclLst(PDeclLst node)
    {
        if(this._declLst_ != null)
        {
            this._declLst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declLst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declLst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declLst_ == child)
        {
            this._declLst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declLst_ == oldChild)
        {
            setDeclLst((PDeclLst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
