/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TActivetok extends Token
{
    public TActivetok()
    {
        super.setText("active");
    }

    public TActivetok(int line, int pos)
    {
        super.setText("active");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TActivetok(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTActivetok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TActivetok text.");
    }
}
