/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TAtomic extends Token
{
    public TAtomic()
    {
        super.setText("atomic");
    }

    public TAtomic(int line, int pos)
    {
        super.setText("atomic");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtomic(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtomic(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtomic text.");
    }
}
