/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TDStep extends Token
{
    public TDStep()
    {
        super.setText("d_step");
    }

    public TDStep(int line, int pos)
    {
        super.setText("d_step");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDStep(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDStep(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDStep text.");
    }
}
