/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TInlinetok extends Token
{
    public TInlinetok()
    {
        super.setText("inline");
    }

    public TInlinetok(int line, int pos)
    {
        super.setText("inline");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInlinetok(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInlinetok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInlinetok text.");
    }
}
