/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TPcValue extends Token
{
    public TPcValue()
    {
        super.setText("pc_value");
    }

    public TPcValue(int line, int pos)
    {
        super.setText("pc_value");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPcValue(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPcValue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPcValue text.");
    }
}
