/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TProcessid extends Token
{
    public TProcessid()
    {
        super.setText("_pid");
    }

    public TProcessid(int line, int pos)
    {
        super.setText("_pid");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProcessid(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProcessid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProcessid text.");
    }
}
