/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TQueryQuery extends Token
{
    public TQueryQuery()
    {
        super.setText("??");
    }

    public TQueryQuery(int line, int pos)
    {
        super.setText("??");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQueryQuery(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQueryQuery(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQueryQuery text.");
    }
}
