/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TRun extends Token
{
    public TRun()
    {
        super.setText("run");
    }

    public TRun(int line, int pos)
    {
        super.setText("run");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRun(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRun(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRun text.");
    }
}
