/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TSkip extends Token
{
    public TSkip()
    {
        super.setText("skip");
    }

    public TSkip(int line, int pos)
    {
        super.setText("skip");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSkip(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSkip(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSkip text.");
    }
}
