/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TTracetok extends Token
{
    public TTracetok()
    {
        super.setText("trace");
    }

    public TTracetok(int line, int pos)
    {
        super.setText("trace");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTracetok(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTracetok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTracetok text.");
    }
}
