/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TUnless extends Token
{
    public TUnless()
    {
        super.setText("unless");
    }

    public TUnless(int line, int pos)
    {
        super.setText("unless");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnless(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnless(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnless text.");
    }
}
