/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.node;

import src.promela.analysis.*;

@SuppressWarnings("nls")
public final class TXr extends Token
{
    public TXr()
    {
        super.setText("xr");
    }

    public TXr(int line, int pos)
    {
        super.setText("xr");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TXr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TXr text.");
    }
}
