/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.promela.lexer;

import java.io.*;
import src.promela.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 84:
                        {
                            @SuppressWarnings("hiding") Token token = new84(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 85:
                        {
                            @SuppressWarnings("hiding") Token token = new85(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 86:
                        {
                            @SuppressWarnings("hiding") Token token = new86(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 87:
                        {
                            @SuppressWarnings("hiding") Token token = new87(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 88:
                        {
                            @SuppressWarnings("hiding") Token token = new88(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 89:
                        {
                            @SuppressWarnings("hiding") Token token = new89(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 90:
                        {
                            @SuppressWarnings("hiding") Token token = new90(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 91:
                        {
                            @SuppressWarnings("hiding") Token token = new91(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 92:
                        {
                            @SuppressWarnings("hiding") Token token = new92(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhiteSpace(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTraditionalComment(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndOfLineComment(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBang(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComplement(line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultop(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShiftop(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqop(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitand(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitor(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBitxor(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelop(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLParenthese(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRParenthese(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeparator(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColonColon(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlusPlus(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinusMinus(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightarrow(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBangBang(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQueryQuery(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQuery(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnderscore(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQuotes(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAt(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TActivetok(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssert(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtomic(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBit(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBool(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBreak(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TByte(line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChanop(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChan(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDStep(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnabled(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEval(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFi(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGoto(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THidden(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInittok(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInlinetok(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLen(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMtypetok(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNevertok(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotrace(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNp(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOd(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOf(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPcValue(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPid(line, pos); }
    Token new71(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrint(text, line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrioritytok(line, pos); }
    Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcessid(line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProctypetok(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProvided(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRun(line, pos); }
    Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShort(line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShow(line, pos); }
    Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSkip(line, pos); }
    Token new80(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTimeout(line, pos); }
    Token new81(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTracetok(line, pos); }
    Token new82(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new83(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTypedef(line, pos); }
    Token new84(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnless(line, pos); }
    Token new85(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXr(line, pos); }
    Token new86(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXs(line, pos); }
    Token new87(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTemplatetok(line, pos); }
    Token new88(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new89(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOver(line, pos); }
    Token new90(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TName(text, line, pos); }
    Token new91(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TByteliteral(text, line, pos); }
    Token new92(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 11, 1}, {12, 12, 4}, {13, 13, 5}, {14, 31, 1}, {32, 32, 6}, {33, 33, 7}, {34, 34, 8}, {35, 36, 1}, {37, 37, 9}, {38, 38, 10}, {39, 39, 1}, {40, 40, 11}, {41, 41, 12}, {42, 42, 13}, {43, 43, 14}, {44, 44, 15}, {45, 45, 16}, {46, 46, 17}, {47, 47, 18}, {48, 57, 19}, {58, 58, 20}, {59, 59, 21}, {60, 60, 22}, {61, 61, 23}, {62, 62, 24}, {63, 63, 25}, {64, 64, 26}, {65, 90, 27}, {91, 91, 28}, {92, 92, 1}, {93, 93, 29}, {94, 94, 30}, {95, 95, 31}, {96, 96, 1}, {97, 97, 32}, {98, 98, 33}, {99, 99, 34}, {100, 100, 35}, {101, 101, 36}, {102, 102, 37}, {103, 103, 38}, {104, 104, 39}, {105, 105, 40}, {106, 107, 27}, {108, 108, 41}, {109, 109, 42}, {110, 110, 43}, {111, 111, 44}, {112, 112, 45}, {113, 113, 27}, {114, 114, 46}, {115, 115, 47}, {116, 116, 48}, {117, 117, 49}, {118, 119, 27}, {120, 120, 50}, {121, 122, 27}, {123, 123, 51}, {124, 124, 52}, {125, 125, 53}, {126, 126, 54}, {127, 255, 1}, },
            {},
            {{9, 9, 55}, {10, 10, 56}, {12, 12, 57}, {13, 13, 58}, {32, 32, 59}, },
            {{9, 32, -4}, },
            {{9, 32, -4}, },
            {{9, 9, 55}, {10, 10, 60}, {12, 32, -4}, },
            {{9, 32, -4}, },
            {{33, 33, 61}, {61, 61, 62}, },
            {{0, 33, 63}, {34, 34, 64}, {35, 65535, 63}, },
            {},
            {{38, 38, 65}, },
            {},
            {},
            {},
            {{43, 43, 66}, },
            {},
            {{45, 45, 67}, {62, 62, 68}, },
            {},
            {{42, 42, 69}, {47, 47, 70}, },
            {{48, 57, 71}, },
            {{58, 58, 72}, },
            {},
            {{60, 60, 73}, {61, 61, 74}, },
            {{61, 61, 75}, },
            {{61, 61, 76}, {62, 62, 77}, },
            {{63, 63, 78}, },
            {},
            {{48, 57, 79}, {65, 90, 80}, {95, 95, 81}, {97, 122, 80}, },
            {},
            {},
            {},
            {{112, 112, 82}, },
            {{48, 95, -29}, {97, 98, 80}, {99, 99, 83}, {100, 114, 80}, {115, 115, 84}, {116, 116, 85}, {117, 122, 80}, },
            {{48, 95, -29}, {97, 104, 80}, {105, 105, 86}, {106, 110, 80}, {111, 111, 87}, {112, 113, 80}, {114, 114, 88}, {115, 120, 80}, {121, 121, 89}, {122, 122, 80}, },
            {{48, 95, -29}, {97, 103, 80}, {104, 104, 90}, {105, 122, 80}, },
            {{48, 90, -29}, {95, 95, 91}, {97, 110, 80}, {111, 111, 92}, {112, 122, 80}, },
            {{48, 95, -29}, {97, 107, 80}, {108, 108, 93}, {109, 109, 94}, {110, 110, 95}, {111, 117, 80}, {118, 118, 96}, {119, 122, 80}, },
            {{48, 95, -29}, {97, 97, 97}, {98, 104, 80}, {105, 105, 98}, {106, 110, 80}, {111, 111, 99}, {112, 116, 80}, {117, 117, 100}, {118, 122, 80}, },
            {{48, 95, -29}, {97, 110, 80}, {111, 111, 101}, {112, 122, 80}, },
            {{48, 104, -35}, {105, 105, 102}, {106, 122, 80}, },
            {{48, 95, -29}, {97, 101, 80}, {102, 102, 103}, {103, 109, 80}, {110, 110, 104}, {111, 122, 80}, },
            {{48, 95, -29}, {97, 100, 80}, {101, 101, 105}, {102, 122, 80}, },
            {{48, 95, -29}, {97, 115, 80}, {116, 116, 106}, {117, 122, 80}, },
            {{48, 100, -43}, {101, 101, 107}, {102, 102, 108}, {103, 110, 80}, {111, 111, 109}, {112, 112, 110}, {113, 122, 80}, },
            {{48, 95, -29}, {97, 99, 80}, {100, 100, 111}, {101, 101, 80}, {102, 102, 112}, {103, 117, 80}, {118, 118, 113}, {119, 122, 80}, },
            {{48, 98, -34}, {99, 99, 114}, {100, 104, 80}, {105, 105, 115}, {106, 113, 80}, {114, 114, 116}, {115, 122, 80}, },
            {{48, 95, -29}, {97, 116, 80}, {117, 117, 117}, {118, 122, 80}, },
            {{48, 103, -36}, {104, 104, 118}, {105, 106, 80}, {107, 107, 119}, {108, 122, 80}, },
            {{48, 100, -43}, {101, 101, 120}, {102, 104, 80}, {105, 105, 121}, {106, 113, 80}, {114, 114, 122}, {115, 120, 80}, {121, 121, 123}, {122, 122, 80}, },
            {{48, 95, -29}, {97, 109, 80}, {110, 110, 124}, {111, 122, 80}, },
            {{48, 95, -29}, {97, 113, 80}, {114, 114, 125}, {115, 115, 126}, {116, 122, 80}, },
            {},
            {{124, 124, 127}, },
            {},
            {},
            {{9, 32, -4}, },
            {{9, 32, -4}, },
            {{9, 32, -4}, },
            {{9, 32, -7}, },
            {{9, 32, -4}, },
            {{9, 32, -4}, },
            {},
            {},
            {{0, 65535, -10}, },
            {},
            {},
            {},
            {},
            {},
            {{0, 9, 128}, {10, 10, 129}, {11, 12, 128}, {13, 13, 130}, {14, 41, 128}, {43, 65535, 128}, },
            {{0, 9, 131}, {10, 10, 132}, {11, 12, 131}, {13, 13, 133}, {14, 65535, 131}, },
            {{48, 57, 71}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{105, 105, 134}, },
            {{48, 115, -44}, {116, 116, 135}, {117, 122, 80}, },
            {{48, 95, -29}, {97, 114, 80}, {115, 115, 136}, {116, 122, 80}, },
            {{48, 110, -40}, {111, 111, 137}, {112, 122, 80}, },
            {{48, 115, -44}, {116, 116, 138}, {117, 122, 80}, },
            {{48, 110, -40}, {111, 111, 139}, {112, 122, 80}, },
            {{48, 100, -43}, {101, 101, 140}, {102, 122, 80}, },
            {{48, 115, -44}, {116, 116, 141}, {117, 122, 80}, },
            {{48, 95, -29}, {97, 97, 142}, {98, 122, 80}, },
            {{48, 114, -86}, {115, 115, 143}, {116, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 114, -86}, {115, 115, 144}, {116, 122, 80}, },
            {{48, 95, -29}, {97, 111, 80}, {112, 112, 145}, {113, 122, 80}, },
            {{48, 95, -29}, {97, 97, 146}, {98, 122, 80}, },
            {{48, 95, -29}, {97, 97, 147}, {98, 122, 80}, },
            {{48, 107, -38}, {108, 108, 148}, {109, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 113, -52}, {114, 114, 149}, {115, 122, 80}, },
            {{48, 107, -38}, {108, 108, 150}, {109, 122, 80}, },
            {{48, 115, -44}, {116, 116, 151}, {117, 122, 80}, },
            {{48, 99, -46}, {100, 100, 152}, {101, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 104, -35}, {105, 105, 153}, {106, 107, 80}, {108, 108, 154}, {109, 115, 80}, {116, 116, 155}, {117, 122, 80}, },
            {{48, 109, -51}, {110, 110, 156}, {111, 122, 80}, },
            {{48, 95, -29}, {97, 120, 80}, {121, 121, 157}, {122, 122, 80}, },
            {{48, 95, -29}, {97, 108, 80}, {109, 109, 158}, {110, 117, 80}, {118, 118, 159}, {119, 122, 80}, },
            {{48, 116, -48}, {117, 117, 160}, {118, 122, 80}, },
            {{48, 115, -44}, {116, 116, 161}, {117, 122, 80}, },
            {{48, 90, -29}, {95, 95, 162}, {97, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 163}, {102, 122, 80}, },
            {{48, 90, -29}, {95, 95, 164}, {97, 122, 80}, },
            {{48, 99, -46}, {100, 100, 165}, {101, 122, 80}, },
            {{48, 104, -35}, {105, 105, 166}, {106, 110, 80}, {111, 111, 167}, {112, 122, 80}, },
            {{48, 109, -51}, {110, 110, 168}, {111, 122, 80}, },
            {{48, 110, -40}, {111, 111, 169}, {112, 122, 80}, },
            {{48, 104, -35}, {105, 105, 170}, {106, 122, 80}, },
            {{48, 108, -109}, {109, 109, 171}, {110, 122, 80}, },
            {{48, 108, -109}, {109, 109, 172}, {110, 122, 80}, },
            {{48, 95, -29}, {97, 97, 173}, {98, 116, 80}, {117, 117, 174}, {118, 122, 80}, },
            {{48, 111, -96}, {112, 112, 175}, {113, 122, 80}, },
            {{48, 107, -38}, {108, 108, 176}, {109, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {},
            {{0, 41, -71}, {42, 42, 177}, {43, 65535, 128}, },
            {{0, 65535, -130}, },
            {{0, 9, 128}, {10, 10, 178}, {11, 65535, -130}, },
            {{0, 65535, -72}, },
            {},
            {{10, 10, 179}, },
            {{100, 100, 180}, },
            {{48, 104, -35}, {105, 105, 181}, {106, 122, 80}, },
            {{48, 100, -43}, {101, 101, 182}, {102, 122, 80}, },
            {{48, 108, -109}, {109, 109, 183}, {110, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 107, -38}, {108, 108, 184}, {109, 122, 80}, },
            {{48, 95, -29}, {97, 97, 185}, {98, 122, 80}, },
            {{48, 100, -43}, {101, 101, 186}, {102, 122, 80}, },
            {{48, 109, -51}, {110, 110, 187}, {111, 122, 80}, },
            {{48, 115, -44}, {116, 116, 188}, {117, 122, 80}, },
            {{48, 100, -43}, {101, 101, 189}, {102, 122, 80}, },
            {{48, 115, -44}, {116, 116, 190}, {117, 122, 80}, },
            {{48, 95, -29}, {97, 97, 80}, {98, 98, 191}, {99, 122, 80}, },
            {{48, 107, -38}, {108, 108, 192}, {109, 122, 80}, },
            {{48, 114, -86}, {115, 115, 193}, {116, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 107, -38}, {108, 108, 194}, {109, 122, 80}, },
            {{48, 110, -40}, {111, 111, 195}, {112, 122, 80}, },
            {{48, 99, -46}, {100, 100, 196}, {101, 122, 80}, },
            {{48, 115, -44}, {116, 116, 197}, {117, 122, 80}, },
            {{48, 104, -35}, {105, 105, 198}, {106, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 111, -96}, {112, 112, 199}, {113, 122, 80}, },
            {{48, 111, -96}, {112, 112, 200}, {113, 122, 80}, },
            {{48, 100, -43}, {101, 101, 201}, {102, 122, 80}, },
            {{48, 107, -38}, {108, 108, 202}, {109, 122, 80}, },
            {{48, 113, -52}, {114, 114, 203}, {115, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 113, -52}, {114, 114, 204}, {115, 122, 80}, },
            {{48, 95, -29}, {97, 117, 80}, {118, 118, 205}, {119, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 109, -51}, {110, 110, 206}, {111, 111, 207}, {112, 122, 80}, },
            {{48, 98, -34}, {99, 99, 208}, {100, 117, 80}, {118, 118, 209}, {119, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 113, -52}, {114, 114, 210}, {115, 118, 80}, {119, 119, 211}, {120, 122, 80}, },
            {{48, 111, -96}, {112, 112, 212}, {113, 122, 80}, },
            {{48, 111, -96}, {112, 112, 213}, {113, 122, 80}, },
            {{48, 100, -43}, {101, 101, 214}, {102, 122, 80}, },
            {{48, 98, -34}, {99, 99, 215}, {100, 122, 80}, },
            {{48, 100, -43}, {101, 101, 216}, {102, 122, 80}, },
            {{48, 100, -43}, {101, 101, 217}, {102, 122, 80}, },
            {{48, 100, -43}, {101, 101, 218}, {102, 122, 80}, },
            {{0, 9, 219}, {10, 10, 220}, {11, 12, 219}, {13, 13, 221}, {14, 41, 219}, {42, 42, 177}, {43, 46, 219}, {47, 47, 222}, {48, 65535, 219}, },
            {{0, 65535, -130}, },
            {},
            {},
            {{48, 117, -166}, {118, 118, 223}, {119, 122, 80}, },
            {{48, 113, -52}, {114, 114, 224}, {115, 122, 80}, },
            {{48, 104, -35}, {105, 105, 225}, {106, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 95, -29}, {97, 106, 80}, {107, 107, 226}, {108, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 227}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 120, -108}, {121, 121, 228}, {122, 122, 80}, },
            {{48, 107, -38}, {108, 108, 229}, {109, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 230}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 231}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 109, -51}, {110, 110, 232}, {111, 122, 80}, },
            {{48, 100, -43}, {101, 101, 233}, {102, 122, 80}, },
            {{48, 115, -44}, {116, 116, 234}, {117, 122, 80}, },
            {{48, 113, -52}, {114, 114, 235}, {115, 122, 80}, },
            {{48, 107, -38}, {108, 108, 236}, {109, 122, 80}, },
            {{48, 95, -29}, {97, 97, 237}, {98, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 95, -29}, {97, 97, 238}, {98, 122, 80}, },
            {{48, 115, -44}, {116, 116, 239}, {117, 122, 80}, },
            {{48, 113, -52}, {114, 114, 240}, {115, 122, 80}, },
            {{48, 115, -44}, {116, 116, 241}, {117, 122, 80}, },
            {{48, 104, -35}, {105, 105, 242}, {106, 122, 80}, },
            {{48, 115, -44}, {116, 116, 243}, {117, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 107, -38}, {108, 108, 244}, {109, 122, 80}, },
            {{48, 110, -40}, {111, 111, 245}, {112, 122, 80}, },
            {{48, 100, -43}, {101, 101, 246}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 99, -46}, {100, 100, 247}, {101, 122, 80}, },
            {{48, 114, -86}, {115, 115, 248}, {116, 122, 80}, },
            {{0, 9, 249}, {10, 10, 250}, {11, 12, 249}, {13, 13, 251}, {14, 41, 249}, {42, 42, 252}, {43, 65535, 249}, },
            {{0, 65535, -221}, },
            {{0, 9, 249}, {10, 10, 253}, {11, 65535, -221}, },
            {},
            {{48, 100, -43}, {101, 101, 254}, {102, 122, 80}, },
            {{48, 115, -44}, {116, 116, 255}, {117, 122, 80}, },
            {{48, 98, -34}, {99, 99, 256}, {100, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 111, -96}, {112, 112, 257}, {113, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 258}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 109, -51}, {110, 110, 259}, {111, 122, 80}, },
            {{48, 100, -43}, {101, 101, 260}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 120, -108}, {121, 121, 261}, {122, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 98, -34}, {99, 99, 262}, {100, 122, 80}, },
            {{48, 107, -38}, {108, 108, 263}, {109, 122, 80}, },
            {{48, 101, -42}, {102, 102, 264}, {103, 108, 80}, {109, 109, 265}, {110, 122, 80}, },
            {{48, 104, -35}, {105, 105, 266}, {106, 122, 80}, },
            {{48, 120, -108}, {121, 121, 267}, {122, 122, 80}, },
            {{48, 99, -46}, {100, 100, 268}, {101, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 95, -29}, {97, 97, 269}, {98, 122, 80}, },
            {{48, 116, -48}, {117, 117, 270}, {118, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 271}, {102, 122, 80}, },
            {{48, 114, -86}, {115, 115, 272}, {116, 122, 80}, },
            {{0, 65535, -221}, },
            {{0, 65535, -221}, },
            {{0, 9, 249}, {10, 10, 273}, {11, 65535, -221}, },
            {{0, 41, -179}, {42, 42, 252}, {43, 65535, -179}, },
            {{0, 65535, -221}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 99, -46}, {100, 100, 274}, {101, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 275}, {102, 122, 80}, },
            {{48, 116, -48}, {117, 117, 276}, {118, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 115, -44}, {116, 116, 277}, {117, 122, 80}, },
            {{48, 111, -96}, {112, 112, 278}, {113, 122, 80}, },
            {{48, 100, -43}, {101, 101, 279}, {102, 122, 80}, },
            {{48, 115, -44}, {116, 116, 280}, {117, 122, 80}, },
            {{48, 115, -44}, {116, 116, 281}, {117, 122, 80}, },
            {{48, 101, -42}, {102, 102, 282}, {103, 122, 80}, },
            {{48, 122, -29}, },
            {{0, 65535, -221}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 100, -43}, {101, 101, 283}, {102, 122, 80}, },
            {{48, 120, -108}, {121, 121, 284}, {122, 122, 80}, },
            {{48, 100, -43}, {101, 101, 285}, {102, 122, 80}, },
            {{48, 99, -46}, {100, 100, 286}, {101, 122, 80}, },
            {{48, 100, -43}, {101, 101, 287}, {102, 122, 80}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
            {{48, 122, -29}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {0, 91, 0, 0, 0, 0, 0, 4, 38, 6, 11, 19, 20, 6, 7, 26, 8, 27, 6, 3, 30, 25, 16, 28, 17, 36, 39, 90, 23, 24, 13, 37, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 21, 12, 22, 5, 0, 0, 0, 0, 0, 0, 34, 10, -1, 92, 14, 31, 32, 25, -1, 2, 3, 29, 9, 18, 10, 18, 9, 35, 90, 90, 90, -1, 90, 90, 90, 90, 90, 90, 90, 90, 90, 50, 90, 90, 90, 90, 90, 55, 90, 90, 90, 90, 58, 90, 90, 90, 90, 90, 90, 90, 67, 68, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 85, 86, 15, -1, -1, -1, 2, 2, 2, -1, 90, 90, 90, 43, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 88, 90, 90, 90, 90, 90, 61, 62, 90, 90, 90, 90, 90, 66, 90, 90, 70, 90, 90, 76, 90, 90, 90, 90, 90, 90, 90, 90, -1, -1, 2, 73, 90, 90, 90, 44, 90, 46, 48, 90, 51, 90, 90, 53, 90, 47, 56, 90, 59, 90, 90, 90, 90, 90, 90, 89, 90, 90, 90, 90, 90, 90, 78, 79, 90, 90, 90, 82, 90, 90, -1, -1, -1, 1, 90, 90, 90, 45, 90, 47, 90, 54, 90, 90, 63, 90, 64, 47, 90, 90, 90, 90, 90, 90, 77, 90, 90, 81, 90, 90, -1, -1, -1, -1, -1, 40, 41, 42, 49, 90, 57, 60, 47, 90, 90, 71, 71, 90, 90, 90, 90, 90, 90, 84, -1, 52, 65, 90, 90, 90, 90, 90, 80, 83, 69, 72, 74, 75, 87, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
